import type { Metadata } from "next";
import { Roboto_Mono as FontMono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/shared/Navbar/Navbar";

const fontMono = FontMono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["400", "500", "700"], // Choose weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-[#0C0A09] text-[#A8A29E] antialiased",
          fontMono.variable
        )}
      >
        <header className="">
          <Navbar />
        </header>
        <main className="container mx-auto max-w-5xl mt-10 pt-16 px-5 lg:px-0">
          {children}
        </main>
      </body>
    </html>
  );
}
